# <div class='alert alert-info'> Creating a simple neural network for iris dataset</div>

In [1]:
#!pip install keras

In [2]:
import numpy as np

In [3]:
from sklearn.datasets import load_iris

In [4]:
d=load_iris()

In [5]:
d

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
d.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
type(d)

sklearn.utils.Bunch

In [8]:
print(d.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [9]:
print(d.target_names)

['setosa' 'versicolor' 'virginica']


In [10]:
print(d.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [11]:
print(d.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

**Lets see the features and the labels information**

In [12]:
x=d.data #Feature

In [13]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [14]:
y=d.target #Labels

In [15]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
x.shape

(150, 4)

In [17]:
d.data.shape

(150, 4)

In [18]:
y.shape

(150,)

In [19]:
d.target.shape

(150,)

## <font color='blue'>One hot encoding using Keras</font>

In [20]:
from keras.utils import to_categorical

In [21]:
y=to_categorical(y)

In [22]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [23]:
y.shape

(150, 3)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.2,random_state=35)

**Using MinMaxScalar**

In [26]:
from sklearn.preprocessing import MinMaxScaler

In [27]:
ss=MinMaxScaler()

In [28]:
sx_train=ss.fit_transform(xtrain)

In [29]:
sx_test=ss.fit_transform(xtest)

In [30]:
sx_train

array([[0.17142857, 0.58333333, 0.0877193 , 0.04166667],
       [0.42857143, 0.5       , 0.66666667, 0.70833333],
       [0.14285714, 0.20833333, 0.61403509, 0.66666667],
       [0.05714286, 0.66666667, 0.        , 0.04166667],
       [0.62857143, 0.41666667, 0.59649123, 0.54166667],
       [0.48571429, 0.25      , 0.80701754, 0.54166667],
       [0.11428571, 0.41666667, 0.07017544, 0.        ],
       [0.85714286, 0.33333333, 0.89473684, 0.75      ],
       [0.57142857, 0.5       , 0.75438596, 0.91666667],
       [0.45714286, 0.08333333, 0.70175439, 0.58333333],
       [0.2       , 0.20833333, 0.35087719, 0.41666667],
       [0.2       , 0.75      , 0.10526316, 0.04166667],
       [0.14285714, 0.45833333, 0.0877193 , 0.04166667],
       [0.34285714, 0.41666667, 0.54385965, 0.5       ],
       [0.8       , 0.66666667, 0.89473684, 1.        ],
       [0.6       , 0.5       , 0.71929825, 0.79166667],
       [0.22857143, 0.875     , 0.0877193 , 0.        ],
       [0.42857143, 0.41666667,

In [31]:
sx_train.max()

1.0

In [32]:
xtrain.max()

7.9

**Now lets built a network with keras**

In [33]:
from keras.models import Sequential  #Sequences of layers
from keras.layers import Dense   #Dense Layer

In [34]:
model= Sequential()

In [35]:
model.add(Dense(8,input_dim=4,activation='relu'))  #10 neurons 
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))   #Output layer
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [36]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [37]:
sx_train.shape

(120, 4)

In [38]:
ytrain.shape

(120, 3)

**Fitting the model**

In [39]:
model.fit(sx_train,ytrain,epochs=150, verbose=2)
#1 epoch is runniung through the entire data set
#indicates the number of passes of the entire training dataset the machine learning algorithm has completed.
#verbose is how much output we want information

Epoch 1/150
4/4 - 0s - loss: 1.0562 - accuracy: 0.3417 - 331ms/epoch - 83ms/step
Epoch 2/150
4/4 - 0s - loss: 1.0490 - accuracy: 0.3417 - 6ms/epoch - 2ms/step
Epoch 3/150
4/4 - 0s - loss: 1.0421 - accuracy: 0.3417 - 6ms/epoch - 1ms/step
Epoch 4/150
4/4 - 0s - loss: 1.0351 - accuracy: 0.3417 - 8ms/epoch - 2ms/step
Epoch 5/150
4/4 - 0s - loss: 1.0285 - accuracy: 0.3417 - 5ms/epoch - 1ms/step
Epoch 6/150
4/4 - 0s - loss: 1.0216 - accuracy: 0.3583 - 8ms/epoch - 2ms/step
Epoch 7/150
4/4 - 0s - loss: 1.0153 - accuracy: 0.4500 - 5ms/epoch - 1ms/step
Epoch 8/150
4/4 - 0s - loss: 1.0090 - accuracy: 0.5667 - 7ms/epoch - 2ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0029 - accuracy: 0.6167 - 5ms/epoch - 1ms/step
Epoch 10/150
4/4 - 0s - loss: 0.9964 - accuracy: 0.6417 - 7ms/epoch - 2ms/step
Epoch 11/150
4/4 - 0s - loss: 0.9902 - accuracy: 0.6500 - 5ms/epoch - 1ms/step
Epoch 12/150
4/4 - 0s - loss: 0.9839 - accuracy: 0.6500 - 6ms/epoch - 1ms/step
Epoch 13/150
4/4 - 0s - loss: 0.9776 - accuracy: 0.6500 - 

Epoch 105/150
4/4 - 0s - loss: 0.4439 - accuracy: 0.8167 - 5ms/epoch - 1ms/step
Epoch 106/150
4/4 - 0s - loss: 0.4409 - accuracy: 0.8583 - 5ms/epoch - 1ms/step
Epoch 107/150
4/4 - 0s - loss: 0.4380 - accuracy: 0.8667 - 5ms/epoch - 1ms/step
Epoch 108/150
4/4 - 0s - loss: 0.4351 - accuracy: 0.8917 - 5ms/epoch - 1ms/step
Epoch 109/150
4/4 - 0s - loss: 0.4322 - accuracy: 0.9000 - 5ms/epoch - 1ms/step
Epoch 110/150
4/4 - 0s - loss: 0.4296 - accuracy: 0.9000 - 4ms/epoch - 1ms/step
Epoch 111/150
4/4 - 0s - loss: 0.4268 - accuracy: 0.9000 - 5ms/epoch - 1ms/step
Epoch 112/150
4/4 - 0s - loss: 0.4238 - accuracy: 0.9000 - 4ms/epoch - 998us/step
Epoch 113/150
4/4 - 0s - loss: 0.4210 - accuracy: 0.9083 - 5ms/epoch - 1ms/step
Epoch 114/150
4/4 - 0s - loss: 0.4182 - accuracy: 0.9000 - 5ms/epoch - 1ms/step
Epoch 115/150
4/4 - 0s - loss: 0.4152 - accuracy: 0.9000 - 4ms/epoch - 992us/step
Epoch 116/150
4/4 - 0s - loss: 0.4127 - accuracy: 0.9083 - 5ms/epoch - 1ms/step
Epoch 117/150
4/4 - 0s - loss: 0.409

**<font color='green'> So after 150 epox we get an accuracy of 94%</font>**

## Lets see how to see the prediction

In [40]:
model.predict(sx_test)

1/1 [==============================] - 0s 76ms/step


array([[1.0755005e-01, 6.9121021e-01, 2.0123976e-01],
       [3.7000712e-02, 6.4352930e-01, 3.1946993e-01],
       [3.7568653e-04, 2.1098284e-01, 7.8864151e-01],
       [1.9323623e-03, 3.0598000e-01, 6.9208771e-01],
       [9.8210806e-01, 1.7210908e-02, 6.8097794e-04],
       [3.6622255e-04, 2.2478664e-01, 7.7484709e-01],
       [9.5162616e-04, 2.5486955e-01, 7.4417877e-01],
       [9.1379970e-02, 6.7710739e-01, 2.3151265e-01],
       [1.6777266e-02, 5.5908251e-01, 4.2414019e-01],
       [9.7388870e-01, 2.4806999e-02, 1.3042830e-03],
       [4.3134090e-02, 6.4184868e-01, 3.1501722e-01],
       [5.5032503e-04, 2.8723773e-01, 7.1221191e-01],
       [9.8172355e-01, 1.7568555e-02, 7.0787570e-04],
       [5.7804934e-04, 2.8560269e-01, 7.1381921e-01],
       [9.3818092e-01, 5.7165869e-02, 4.6532541e-03],
       [1.1685911e-03, 2.6043305e-01, 7.3839837e-01],
       [1.7526429e-02, 4.8333296e-01, 4.9914068e-01],
       [9.5245433e-01, 4.4087306e-02, 3.4583523e-03],
       [9.5612240e-01, 4.073

**It is splitting based on probabilities by default**

In [42]:
predict_x=model.predict(sx_test) 

1/1 [==============================] - 0s 15ms/step


In [44]:
classes_x=np.argmax(predict_x,axis=1)

In [45]:
classes_x

array([1, 1, 2, 2, 0, 2, 2, 1, 1, 0, 1, 2, 0, 2, 0, 2, 2, 0, 0, 0, 1, 1,
       2, 1, 0, 0, 0, 2, 0, 2], dtype=int64)

**Now it predicting based on classes**

In [50]:
yy=ytest.argmax(axis=1)

In [51]:
yy

array([1, 1, 2, 1, 0, 2, 2, 1, 1, 0, 1, 2, 0, 2, 0, 2, 1, 0, 0, 0, 1, 1,
       2, 1, 0, 0, 0, 2, 0, 2], dtype=int64)

**Time to check how well our model perfomed**

In [49]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [52]:
confusion_matrix(yy,classes_x)

array([[11,  0,  0],
       [ 0,  8,  2],
       [ 0,  0,  9]], dtype=int64)

In [54]:
print(classification_report(yy,classes_x))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.80      0.89        10
           2       0.82      1.00      0.90         9

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.95      0.93      0.93        30



In [55]:
accuracy_score(yy,classes_x)

0.9333333333333333

**Wow! 93%**

## To save the model extension would be h5

In [56]:
model.save("Model_one.h5")

**Now if the next day you want to run the same model**

In [58]:
from keras.models import load_model

In [59]:
new_model= load_model("Model_one.h5")